#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication checkMesh
runApplication topoSet
runApplication foamRun

# dcMetricsPlus is optional but recommended. Compile it from ../../src first.
if command -v dcMetricsPlus >/dev/null 2>&1; then
    runApplication dcMetricsPlus -latestTime
else
    echo "dcMetricsPlus not found. Compile it from src/dcMetricsPlus with wmake."
fi
