#!/bin/sh
cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf constant/polyMesh/sets constant/polyMesh/cellZones constant/polyMesh/pointZones constant/polyMesh/faceZones
rm -rf postProcessing
rm -f log.*
