#!/usr/bin/env python3
"""
Collect per-rack dcMetricsPlus outputs generated by v02_generate_per_rack_metrics.py.

Expected per-rack structure:
    CASE/postProcessing/dcMetricsPlus_perRack/L1/<time>/metrics.csv
    CASE/postProcessing/dcMetricsPlus_perRack/L2/<time>/metrics.csv
    ...

If these files do not exist, run:
    python3 scripts/v02_generate_per_rack_metrics.py
first. Yes, the collector only collects. Astonishingly literal.
"""

import argparse
from pathlib import Path
import sys

import pandas as pd

RACKS = ["L1", "L2", "L3", "R1", "R2", "R3"]
RACK_POWER_COLUMNS = {
    "L1": "rack_L1_power_W",
    "L2": "rack_L2_power_W",
    "L3": "rack_L3_power_W",
    "R1": "rack_R1_power_W",
    "R2": "rack_R2_power_W",
    "R3": "rack_R3_power_W",
}

PER_RACK_METRICS = [
    "TavgRackInlet",
    "T95RackInlet",
    "TmaxRackInlet",
    "rackInletHotspotFraction",
    "rackInletHotspotVolume",
    "nRackInletCells",
]


def parse_float_time(name: str):
    try:
        return float(name)
    except ValueError:
        return None


def resolve_case_dir(case_row, base_dir: Path) -> Path:
    candidates = []
    for key in ["caseDir", "caseID", "caseName"]:
        value = str(case_row.get(key, "")).strip()
        if value and value.lower() != "nan":
            p = Path(value)
            candidates.append(p if p.is_absolute() else base_dir / p)

    for p in candidates:
        if p.exists() and p.is_dir():
            return p

    case_id = str(case_row.get("caseID", "")).strip()
    if case_id:
        matches = sorted(base_dir.glob(f"{case_id}*"))
        matches = [m for m in matches if m.is_dir()]
        if len(matches) == 1:
            return matches[0]

    raise FileNotFoundError(f"Cannot resolve case directory for {case_row.get('caseID')}")


def discover_rack_metrics_files(case_dir: Path, rack: str, start_time: float, end_time: float):
    root = case_dir / "postProcessing" / "dcMetricsPlus_perRack" / rack
    if not root.exists():
        return []

    files = []
    for metrics_path in root.glob("*/metrics.csv"):
        folder_time = parse_float_time(metrics_path.parent.name)
        if folder_time is None:
            continue
        if start_time <= folder_time <= end_time:
            files.append((folder_time, metrics_path))

    return sorted(files, key=lambda x: x[0])


def read_rack_metrics(case_row, case_dir: Path, rack: str, folder_time: float, metrics_path: Path):
    df = pd.read_csv(metrics_path)
    if df.empty:
        print(f"WARNING: empty {metrics_path}", file=sys.stderr)
        return None

    row = df.iloc[0].to_dict()

    row_time = row.get("time", folder_time)
    try:
        row_time = float(row_time)
    except Exception:
        row_time = float(folder_time)

    row["caseID"] = str(case_row["caseID"])
    row["caseName"] = str(case_row["caseName"])
    row["caseDir"] = str(case_dir)
    row["rackID"] = rack
    row["timeSample"] = row_time
    row["rackPowerW"] = float(case_row[RACK_POWER_COLUMNS[rack]])

    return row


def summarize(group: pd.DataFrame) -> pd.Series:
    out = {}
    first = group.iloc[0]
    out["caseID"] = first["caseID"]
    out["caseName"] = first["caseName"]
    out["caseDir"] = first["caseDir"]
    out["rackID"] = first["rackID"]
    out["rackPowerW"] = first["rackPowerW"]

    for col in PER_RACK_METRICS:
        if col not in group.columns:
            continue
        out[f"{col}_mean"] = group[col].mean()
        out[f"{col}_std"] = group[col].std(ddof=1) if len(group) > 1 else 0.0
        out[f"{col}_min"] = group[col].min()
        out[f"{col}_max"] = group[col].max()
        if (group["timeSample"] == 8000).any():
            out[f"{col}_final8000"] = group.loc[group["timeSample"] == 8000, col].iloc[0]
        else:
            latest_idx = group["timeSample"].idxmax()
            out[f"{col}_finalLatest"] = group.loc[latest_idx, col]

    out["nLateSamples"] = len(group)
    out["lateTimeMin"] = group["timeSample"].min()
    out["lateTimeMax"] = group["timeSample"].max()

    return pd.Series(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--case-matrix", default="results/tables/v02_case_matrix.csv")
    parser.add_argument("--case-root", default=".")
    parser.add_argument("--start-time", type=float, default=4000.0)
    parser.add_argument("--end-time", type=float, default=8000.0)
    parser.add_argument("--cases", nargs="*", default=None, help="Optional case IDs to collect")
    parser.add_argument("--racks", nargs="*", default=RACKS, help="Optional rack IDs to collect")
    parser.add_argument("--out-raw", default="results/tables/v02_per_rack_late_times_raw.csv")
    parser.add_argument("--out-summary", default="results/tables/v02_per_rack_late_average.csv")
    args = parser.parse_args()

    case_matrix_path = Path(args.case_matrix)
    if not case_matrix_path.exists():
        raise FileNotFoundError(f"Missing case matrix: {case_matrix_path}")

    case_matrix = pd.read_csv(case_matrix_path)
    base_dir = Path(args.case_root).resolve()
    selected_cases = set(args.cases) if args.cases else None

    rows = []
    missing_case_rack_count = 0

    for _, case_row in case_matrix.iterrows():
        case_id = str(case_row["caseID"])
        if selected_cases and case_id not in selected_cases:
            continue

        case_dir = resolve_case_dir(case_row, base_dir)

        for rack in args.racks:
            files = discover_rack_metrics_files(case_dir, rack, args.start_time, args.end_time)
            if not files:
                missing_case_rack_count += 1
                print(
                    f"WARNING: missing per-rack metrics for {case_id}/{rack}: "
                    f"{case_dir}/postProcessing/dcMetricsPlus_perRack/{rack}/*/metrics.csv",
                    file=sys.stderr,
                )
                continue

            for folder_time, metrics_path in files:
                row = read_rack_metrics(case_row, case_dir, rack, folder_time, metrics_path)
                if row is not None:
                    rows.append(row)

    if not rows:
        raise RuntimeError(
            "No per-rack metrics found. Run this first from the parameterstudy root:\n"
            "    python3 scripts/v02_generate_per_rack_metrics.py\n"
            "or, for only overloaded cases:\n"
            "    python3 scripts/v02_generate_per_rack_metrics.py --cases C05 C08 C09\n"
            "Then rerun this collector."
        )

    raw = pd.DataFrame(rows)
    summary = (
        raw.groupby(["caseID", "rackID"], sort=False)
        .apply(summarize)
        .reset_index(drop=True)
    )

    Path(args.out_raw).parent.mkdir(parents=True, exist_ok=True)
    raw.to_csv(args.out_raw, index=False)
    summary.to_csv(args.out_summary, index=False)

    print(f"Wrote {args.out_raw}")
    print(f"Wrote {args.out_summary}")
    if missing_case_rack_count:
        print(f"NOTE: {missing_case_rack_count} case/rack combinations were missing and skipped.")


if __name__ == "__main__":
    main()
